### DISCUSSION TITLE
Light Planner 2025 - Only scheduling - (No Todo pages, No Notes pages, No Daily reflect, and No daily notes)

### DISCUSSION THREAD

**Discussion by wolfallein** [kudrykv/latex-yearly-planner#158] [Show and tell]
Hi,
First, thank you for this amazing work!
I used the `rubify2` branch and that version really improves the customization aspect of the planner. 😄 

I wanted a light version of the original planner, without the Todo pages, Notes pages, daily reflect, and daily notes.
The idea is to have only the scheduling aspects. My plan is to create a link to other Notebooks if I need more space.

This approach saves file size and pages I'll never use. I was having problems with my device because it was taking too long to export to PDF and upload it.

I also added an option to add a space on top of the side navigation. I like to keep the shortcut of my toolbar there (Note Air 3).

<details>

<summary>Diff</summary>

```
diff --git a/lib/latex_yearly_planner/planners/mos/pages/face.rb b/lib/latex_yearly_planner/planners/mos/pages/face.rb
index 63956c8..27ae229 100644
--- a/lib/latex_yearly_planner/planners/mos/pages/face.rb
+++ b/lib/latex_yearly_planner/planners/mos/pages/face.rb
@@ -94,6 +94,7 @@ module LatexYearlyPlanner
             def to_typst
               <<~TYPST
                 pad(
+                  top: #{mosnav[:top_pad]},
                   left: #{mosnav[:left_pad]},
                   right: #{mosnav[:right_pad]},
                   rotate(
```
</details>

Configuration used:

<details>
<summary>158x210-rightie_light.yaml</summary>

```
version: '0.1'

template: mos
locale: en

compiler:
  ghostscript:
    enable: true

document:
  layout:
    dimensions:
      width: 158mm
      height: 210mm

    margin:
      top: 3mm
      bottom: 0mm
      left: 0mm
      right: 3mm

  text:
    size: 10pt

planner:
  parameters:
    start_date: 2025, January
    end_date: 2025, December
    weekday_start: Sunday

    heading_size: 16pt
    pattern: dotted

  objects:
    mos_layout:
      side_menu: left
      mos_nav_width: 10mm
      heading_height: 10mm

    mos_nav:
      left_pad: 0mm
      right_pad: 2mm
      top_pad: 10mm
      rotate: 270deg
      reverse_array_internals: true
      reverse_arrays: true
      quarter_width: 1.1fr
      month_width: 1fr

    heading:
      bottom_pad: 3mm
      put_extra_items: left
      title_position: left

    little_calendar:
      with_week_numbers: true
      week_number_placement: left
      inset: "(x: 1.2mm, y: 1.5mm)"
      underline_weekdays: true
      sideline_week_numbers: true
      highlight_week: true
      link_to_month: true
      link_to_week: true
      take_full_width: true

    large_calendar:
      with_week_numbers: true
      week_number_placement: left
      link_to_week: true
      weekday_names: full
      heading_height: 6mm
      week_row_height: 25mm
      week_cell_rotate: 270deg

  sections:
    - title:
        enabled: true
        parameters:
          name: "2025\n\nPlanner"
          font_size: 48pt

    - annual:
        enabled: true
        parameters:
          months_per_page: 12
          months_per_row: 3
        objects:
          little_calendar:
            take_full_width: false

    - quarterly:
        enabled: true
        parameters:
          months_width: 4.5cm
          gap_width: 5mm
          reverse_columns: false

    - monthly:
        enabled: true
        parameters:
          gap_width: 5mm

    - weekly:
        enabled: true
        parameters:
          first_row_height: 8mm
          rest_row_height: 9mm

    - daily:
        enabled: true
        parameters:
          left_column_width: 4.5cm

          left_column_items: [ schedule, gap, little_calendar ]
          right_column_items: [ top_priorities, notes ]

          schedule_strftime: '%k'
          schedule_from_hour: 8
          schedule_to_hour: 20
          schedule_trailing_30min: true

          gap_width: 2mm
          priorities_number: 8

          notes_height: 100%
          personal_notes_height: 0%

          daily_notes_explicit_links: "false"

    - daily_notes:
        enabled: false
        parameters:
          pages_per_day: 1

    - daily_reflect:
        enabled: false
        parameters:
          left_column_width: 1fr
          gap_width: 5mm

          left_column_items: [ my_best_thing ]
          right_column_items: [ my_goals, my_grateful ]
          bottom_merged: [ my_daily_log ]

          my_goals:
            height: 2.5cm

          my_best_thing:
            height: 6.5cm

          my_grateful:
            height: 3cm

          my_daily_log:
            height: 100%

    - todo_index:
        enabled: false
        parameters:
          pages: 2
          columns: 2
          rows: 25
          gap_width: 2mm
          cell_height: 7mm

    - todo_pages:
        enabled: false
        parameters:
          columns: 2
          rows: 3
          gap_width: 2mm

          items_in_group: 8
          todo_height: 7mm

    - notes_index:
        enabled: false
        parameters:
          pages: 2
          columns: 2
          rows: 25
          gap_width: 2mm
          cell_height: 7mm

    - notes_pages:
        enabled: false
```
</details>

[index.pdf](https://github.com/user-attachments/files/19647540/index.pdf)

**Comment by ghost** [comment]
I am trying to recreate this, but failing. Can you show your CFG?

**Reply by wolfallein** [reply]
The configuration file is on original post, but I'll rewrite here.
Here are all the commands I used to get it on Debian:

```
sudo apt install ruby-dev
git clone https://github.com/kudrykv/latex-yearly-planner.git --branch=rubify2
cd latex-yearly-planner/
```

Create `config/158x210-rightie_light.yaml` file:

```
nano config/158x210-rightie_light.yaml
```
Add this content to the file:
<details>
 <summary>158x210-rightie_light.yaml</summary>

 ```
version: '0.1'

template: mos
locale: en

compiler:
  ghostscript:
    enable: true

document:
  layout:
    dimensions:
      width: 158mm
      height: 210mm

    margin:
      top: 3mm
      bottom: 0mm
      left: 0mm
      right: 3mm

  text:
    size: 10pt

planner:
  parameters:
    start_date: 2025, January
    end_date: 2025, December
    weekday_start: Sunday

    heading_size: 16pt
    pattern: dotted

  objects:
    mos_layout:
      side_menu: left
      mos_nav_width: 10mm
      heading_height: 10mm

    mos_nav:
      left_pad: 0mm
      right_pad: 2mm
      top_pad: 10mm
      rotate: 270deg
      reverse_array_internals: true
      reverse_arrays: true
      quarter_width: 1.1fr
      month_width: 1fr

    heading:
      bottom_pad: 3mm
      put_extra_items: left
      title_position: left

    little_calendar:
      with_week_numbers: true
      week_number_placement: left
      inset: "(x: 1.2mm, y: 1.5mm)"
      underline_weekdays: true
      sideline_week_numbers: true
      highlight_week: true
      link_to_month: true
      link_to_week: true
      take_full_width: true

    large_calendar:
      with_week_numbers: true
      week_number_placement: left
      link_to_week: true
      weekday_names: full
      heading_height: 6mm
      week_row_height: 25mm
      week_cell_rotate: 270deg

  sections:
    - title:
        enabled: true
        parameters:
          name: "2025\n\nPlanner"
          font_size: 48pt

    - annual:
        enabled: true
        parameters:
          months_per_page: 12
          months_per_row: 3
        objects:
          little_calendar:
            take_full_width: false

    - quarterly:
        enabled: true
        parameters:
          months_width: 4.5cm
          gap_width: 5mm
          reverse_columns: false

    - monthly:
        enabled: true
        parameters:
          gap_width: 5mm

    - weekly:
        enabled: true
        parameters:
          first_row_height: 8mm
          rest_row_height: 9mm

    - daily:
        enabled: true
        parameters:
          left_column_width: 4.5cm

          left_column_items: [ schedule, gap, little_calendar ]
          right_column_items: [ top_priorities, notes ]

          schedule_strftime: '%k'
          schedule_from_hour: 8
          schedule_to_hour: 20
          schedule_trailing_30min: true

          gap_width: 2mm
          priorities_number: 8

          notes_height: 100%
          personal_notes_height: 0%

          daily_notes_explicit_links: "false"

    - daily_notes:
        enabled: false
        parameters:
          pages_per_day: 1

    - daily_reflect:
        enabled: false
        parameters:
          left_column_width: 1fr
          gap_width: 5mm

          left_column_items: [ my_best_thing ]
          right_column_items: [ my_goals, my_grateful ]
          bottom_merged: [ my_daily_log ]

          my_goals:
            height: 2.5cm

          my_best_thing:
            height: 6.5cm

          my_grateful:
            height: 3cm

          my_daily_log:
            height: 100%

    - todo_index:
        enabled: false
        parameters:
          pages: 2
          columns: 2
          rows: 25
          gap_width: 2mm
          cell_height: 7mm

    - todo_pages:
        enabled: false
        parameters:
          columns: 2
          rows: 3
          gap_width: 2mm

          items_in_group: 8
          todo_height: 7mm

    - notes_index:
        enabled: false
        parameters:
          pages: 2
          columns: 2
          rows: 25
          gap_width: 2mm
          cell_height: 7mm

    - notes_pages:
        enabled: false
 ```

</details>

Add the top margin if you need:
```
nano lib/latex_yearly_planner/planners/mos/pages/face.rb
```

<details>
<summary>lib/latex_yearly_planner/planners/mos/pages/face.rb</summary>

Here is the diff, you need to add `top: #{mosnav[:top_pad]},` at line 97.

```
diff --git a/lib/latex_yearly_planner/planners/mos/pages/face.rb b/lib/latex_yearly_planner/planners/mos/pages/face.rb
index 63956c8..27ae229 100644
--- a/lib/latex_yearly_planner/planners/mos/pages/face.rb
+++ b/lib/latex_yearly_planner/planners/mos/pages/face.rb
@@ -94,6 +94,7 @@ module LatexYearlyPlanner
             def to_typst
               <<~TYPST
                 pad(
+                  top: #{mosnav[:top_pad]},
                   left: #{mosnav[:left_pad]},
                   right: #{mosnav[:right_pad]},
                   rotate(
```

</details>

Install the dependencies and execute:

```
bundle install --path .gem
bundle exec exe/latex_yearly_planner generate config/158x210-rightie_light.yaml
```

Your generated file should be on `out/index.pdf`
